version: '3'
services:
  apprenant-service:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/apprenantDB
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
